language: python
python:
- '3.6'
install:
- make install-dev
script:
- make coverage
deploy:
  provider: pypi
  user: vlttnv
  on:
    tags: true
  password:
    secure: OtOelP7jHCVtdbiC3aUwzODv5AjL3xJInD0lhs0byjz1sHpycb/+x5qyemz/mEvRGS30qeDJDNxec8qS8lLhBxN2Bj8PoWvoJ0zLcdM3OUn36xMseGE3Mn9e/53FCofyhYx3Q/bT+ccIJ20Y1JO8osn9Q4Qk+pFZ4L1/tYNG5Lv96OtifEYs2naYtH2F9Hn+LnroF8+kMEFbu4EyOpfPamHGTfbq3FA8Ik5qWi8CeKPHj0r5RG+9aSPT9q7c8erU9flB2QgKIcMjSb+4WqV1WaDJNNbEjfxEdqLFv/xR9sPJvm+Bhf7jWW0hY84lpIS/dtea43jgx6MlJ5yIfw5PuvzB25pt+a5JewKNUC/wFTTDor8Kg+sFUelRdM8/WdfL9gUQuF7ZOSKykNYy7q7taxfQGFVtUPluKBu0wcgopxTUB6ZfYnIfLyKiWcHpbBJkVRCJh+2ENRnECofMVBjlnsQFh+uFGvMRSXvkTSbfJCf9PFgVjT3PiJIkhsYHe3OnUROH7bbgICHKbA/mCeuIGo9VYXAoaZv00tiIy4mRRBPh1aYiZH8tMSntReQkkSbqsCXkTwS9/Louiy179+w/RkLYIvb2XJXx1q7fzDgGnwDRldibep+Fjx1LnyNdxZuV//TKRGHdRy+haeWh6wV3OeSp9mAhluO8v2wPJ1RbpzI=
