language: python
python:
- '3.6'
install:
- make install-dev
script:
- make coverage
deploy:
  provider: pypi
  user: vlttnv
  password:
    secure: ecure: m9+ZTVnXMsxzLdFqyZLq1awwD3sQT6/EcImjyblA68DcXCsxAHxqTug4IkUrzFpH0v8lI4UE+SJ3kBZGNYzCbH4IpOjAWcx/2ymr3svLWWT17gTesbCarUI/hKHJLC8HFNSX1KxLT6hznFCqWGcm1tLoUGZVfwI1pjy1RaSZVv1oXSOaP0EAE8c1+0sov3AEZnC8k1/jHdRGLSF5dOtypniVASpLpxBR1OER1lI6QLqeOQc5+6XLcusFHeBqnnXTh8LkAUBpYN1rLEjwBP1lvvuEoTB3ruuDIvzU3b7svD2MKQfp9ExbmwwEvm+jOqTfuR0GXV0u44ZIdZXahAmR6kbW1AUEkNDGrIVEtu8xABeSiu1sMcjj6q4RBqGmnHGHQNL6la6kmPtKzNlfl+4F/0V4LnGtq0ZHdO+4nUv9znzN5nIzQ/3lZX7WimYXjBZT+HB4bEQBw0qPXgCOrKUqjJAE1hqEXbHH66dikSvxCZ65OAviJKJ1l/bWFU5rCXSMR+L8YViRM1k2JqvhA5Yf/9Tb7ILmXRldTkZvwe1c2t92xgY91fa7AWyJ6ePK2Nhj0Hp0ub55F5tonxPSK777WWIi5IJGd9n8Yv6Ag9ORQZvWBYGKgJ7mOkAVDC20N3XJcphep8Q5nFzmRUrom5k6L1/yiUYCDRRGkcEKwuLmDo8=
  on:
    tags: true
